//! End-to-end proof that one derived struct drives full CRUD — and keyset
//! cursoring — across dialects, unchanged.
//!
//! SQLite (in-memory) always runs. MySQL runs too when `TEST_DATABASE_URL` is
//! set (the CI MySQL container), which is where dialect-specific type quirks
//! such as `BIGINT UNSIGNED` → `u64` actually bite — so they are MySQL-verified.
#![cfg(feature = "sea-orm-executor")]

use chrono::{TimeZone, Utc};
use rainier_drivers::sql::SeaOrmExecutor;
use rainier_orm::{repo, schema, Entity, Executor, PoolConfig};
use sea_orm::{ConnectionTrait, Database};

#[derive(Debug, Clone, PartialEq, Entity)]
#[orm(table = "widgets")]
struct Widget {
    #[orm(pk, auto_increment)]
    id: u64,
    name: String,
    // nullable, inferred from Option
    note: Option<String>,
    quantity: u64,
    weight: f64,
    active: bool,
    #[orm(column = "created_at")]
    created: chrono::DateTime<Utc>,
}

async fn create_table(exec: &SeaOrmExecutor) {
    let ddl = schema::create_table_ddl::<Widget>(exec.dialect());
    exec.execute(&ddl, vec![]).await.expect("create table");
}

async fn run_crud(exec: SeaOrmExecutor) {
    create_table(&exec).await;

    let created = Utc.with_ymd_and_hms(2026, 6, 3, 12, 0, 0).unwrap();
    let mut w = Widget {
        id: 0, // assigned by the DB
        name: "sprocket".into(),
        note: None,
        quantity: 7,
        weight: 3.5,
        active: true,
        created,
    };

    // INSERT — autogenerated key comes back.
    let id = repo::insert(&exec, &w).await.expect("insert");
    assert!(id > 0, "expected an auto-increment id, got {id}");
    w.id = id as u64;

    // FIND — round-trips every column type, including the NULL note and the
    // unsigned quantity.
    let got: Widget = repo::find_by_pk(&exec, w.id).await.expect("find").expect("row present");
    assert_eq!(got, w);

    // UPDATE — flip the nullable and unsigned fields.
    w.note = Some("restocked".into());
    w.quantity = 42;
    w.active = false;
    let affected = repo::update(&exec, &w).await.expect("update");
    assert_eq!(affected, 1);
    let got: Widget = repo::find_by_pk(&exec, w.id).await.expect("find").expect("row present");
    assert_eq!(got.note.as_deref(), Some("restocked"));
    assert_eq!(got.quantity, 42);
    assert!(!got.active);

    // DELETE.
    let affected = repo::delete_by_pk::<Widget, _, _>(&exec, w.id).await.expect("delete");
    assert_eq!(affected, 1);
    let gone: Option<Widget> = repo::find_by_pk(&exec, w.id).await.expect("find");
    assert!(gone.is_none());

    // CURSOR — seed 25 rows, walk in pages of 10, expect 10 + 10 + 5 then end.
    let created = Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap();
    for n in 0..25u64 {
        let row = Widget {
            id: 0,
            name: format!("w{n}"),
            note: None,
            quantity: n,
            weight: n as f64,
            active: true,
            created,
        };
        repo::insert(&exec, &row).await.expect("seed insert");
    }

    let mut cur = repo::cursor::<Widget, _>(&exec, 10);
    let mut page_sizes = vec![];
    let mut total = 0usize;
    let mut last_id = 0u64;
    while let Some(page) = cur.next_page().await.expect("page") {
        page_sizes.push(page.len());
        for row in &page {
            // keyset order: strictly ascending primary key, no dupes/skips.
            assert!(row.id > last_id, "cursor went backwards: {} !> {}", row.id, last_id);
            last_id = row.id;
        }
        total += page.len();
    }
    assert_eq!(total, 25);
    assert_eq!(page_sizes, vec![10, 10, 5]);

    // Resume from a checkpoint: a fresh cursor seeded with `after(13th id)`
    // yields the tail only.
    let all: Vec<Widget> = repo::all(&exec).await.expect("all");
    let midpoint = all[11].id; // 12th row
    let mut tail = repo::cursor::<Widget, _>(&exec, 100).after(midpoint);
    let rest = tail.next_page().await.expect("tail").expect("some");
    assert_eq!(rest.len(), all.len() - 12);
    assert!(rest.iter().all(|r| r.id > midpoint));
}

#[tokio::test]
async fn crud_sqlite_in_memory() {
    let db = Database::connect("sqlite::memory:").await.expect("connect sqlite");
    run_crud(SeaOrmExecutor::new(db)).await;
}

#[tokio::test]
async fn crud_sqlite_pooled_serverless() {
    // The serverless preset is max_connections=1 — which also keeps an
    // in-memory SQLite (one db per connection) coherent across the round-trip.
    let exec = SeaOrmExecutor::connect("sqlite::memory:", &PoolConfig::serverless())
        .await
        .expect("pooled connect");
    run_crud(exec).await;
}

#[tokio::test]
async fn crud_mysql_container() {
    let Ok(url) = std::env::var("TEST_DATABASE_URL") else {
        eprintln!("TEST_DATABASE_URL unset — skipping MySQL dialect check");
        return;
    };
    let db = Database::connect(&url).await.expect("connect mysql");
    // Isolate from other runs / the in-memory test's table name.
    let _ = db
        .execute(sea_orm::Statement::from_string(
            sea_orm::DatabaseBackend::MySql,
            "DROP TABLE IF EXISTS widgets",
        ))
        .await;
    run_crud(SeaOrmExecutor::new(db)).await;
}
